set pad_wire_necking on
bus diagonal
fanout 10
route 100
clean 7
route 100 16
clean 7
route 100 16
clean 7
route 100 16
clean 7
route 100 16
clean 7
route 100 16
clean 7
route 100 16
clean 7
route 100 16
clean 7
route 100 16
clean 7
route 100 16
clean 7
route 100 16
clean 7
route 100 16
clean 7
route 100 16
clean 7
route 100 16
clean 7
route 100 16
clean 7
route 100 16
clean 7
route 100 16
clean 7
route 100 16
clean 7
route 100 16
clean 7
route 100 16
clean 7
route 100 16
clean 7
filter 5
recorner diagonal
status_file
